<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCEzAk8G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCEzAk8G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCEzAk8G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCEzAk8G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCEzAk8G\App_KernelDevDebugContainer([
    'container.build_hash' => 'CEzAk8G',
    'container.build_id' => '1669f73c',
    'container.build_time' => 1601041202,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCEzAk8G');
