<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGcEBxVp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGcEBxVp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGcEBxVp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGcEBxVp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGcEBxVp\App_KernelDevDebugContainer([
    'container.build_hash' => 'GcEBxVp',
    'container.build_id' => '1b9d72c4',
    'container.build_time' => 1600942261,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGcEBxVp');
