<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK6KinfV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK6KinfV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK6KinfV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK6KinfV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK6KinfV\App_KernelDevDebugContainer([
    'container.build_hash' => 'K6KinfV',
    'container.build_id' => 'a4e233a3',
    'container.build_time' => 1600778013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK6KinfV');
